#!/usr/bin/env python
#installer script for my Mac computers

#Install Homebrew

if ! command -v brew >/dev/null; then
  echo "Installing Homebrew ..."
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
  echo "Homebrew already installed. Skipping ..."
fi

#Install Homebrew programs
./brew.sh

#Install Homebrew cask programs
./brew-cask.sh

#Install Atom packages
./atom.sh

#Set Environment variables
export EDITOR="/usr/local/bin/nvim"

#COMPLETE
echo "All installed!"
